IF OBJECT_ID('FormatDateMMDDYYYY') IS NOT NULL
    DROP FUNCTION FormatDateMMDDYYYY;
GO

CREATE FUNCTION FormatDateMMDDYYYY
(
    @InputDateTime DATETIME
)
RETURNS NVARCHAR(10)
AS
BEGIN
    RETURN FORMAT(@InputDateTime, 'MM/dd/yyyy');
END;
GO