IF OBJECT_ID('FormatDateYYYYMMDD') IS NOT NULL
    DROP FUNCTION FormatDateYYYYMMDD;
GO

CREATE FUNCTION FormatDateYYYYMMDD
(
    @InputDateTime DATETIME
)
RETURNS NVARCHAR(8)
AS
BEGIN
    RETURN FORMAT(@InputDateTime, 'yyyyMMdd');
END;
GO